version: "3.7"

networks:
  shared-network:
    driver: bridge
    
services:
  api:
    networks:
      - shared-network
    depends_on: 
      - db
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment: 
     - DB_DSN=postgres://postgres:mysecretpassword@db:5432/sale?sslmode=disable
  db:
    networks:
      - shared-network
    # image: postgres:12.4-alpine
    build:
      context: .
      dockerfile: pg.dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=sale
    ports:
      - "5452:5432"