version: "3.7"

networks:
  shared-network:
    driver: bridge
    
services:
  api:
    networks:
      - shared-network
    depends_on: 
      - db
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8080"
  db:
  # image: postgres:12.4-alpine
    networks:
    - shared-network
    build:
      context: .
      dockerfile: tk.dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=tonkla727426
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=sale
    ports:
      - "5452:5432"