FROM golang:1.14-alpine AS builder
WORKDIR /app
COPY go.mod  go.sum /
RUN go mod download
COPY cmd cmd
COPY service service
RUN ls -lrt
RUN pwd
RUN go build -o main cmd/main.go
FROM alpine
WORKDIR /app/
COPY --from=builder /build/main .
EXPOSE 8080
CMD [ "./main" ]
